controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: forward_command_controller/ForwardCommandController

    gripper_controller:
      type: forward_command_controller/ForwardCommandController

arm_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      - joint_z
      - joint_gripper_base
    interface_name: position

gripper_controller:
  ros__parameters:
    joints:
      - joint_finger_1
    interface_name: position